### ISSUE TITLE
0.18.3 failing tests: poisoned cmd mutex!: PoisonError 

### ISSUE THREAD

**Issue by kpcyrd** [rustsec/rustsec#1054]
While preparing the v0.18.3 I noticed the tests may file (this happened during a second build after minor changes in package metadata but not the first build, so I suspect it's not 100% reliable/deterministic):

```
+ run: cargo run -- audit --db /tmp/.tmpTD7BQa --file /build/cargo-audit/src/rustsec-cargo-audit-v0.18.3/cargo-audit/tests/support/base64_vuln/Cargo.lock --json --ignore RUSTSEC-2017-0004
test advisories_found_but_ignored_json has been running for over 60 seconds
test advisories_found_exit_error has been running for over 60 seconds
test advisories_found_json has been running for over 60 seconds
test no_advisories_found_empty_json has been running for over 60 seconds
test no_advisories_found_exit_success has been running for over 60 seconds
test no_lockfile_exit_error has been running for over 60 seconds
test notice_advisories_found_json has been running for over 60 seconds
test unmaintained_advisories_found_json has been running for over 60 seconds
test unmaintained_exit_failure_deny_warnings has been running for over 60 seconds
test unmaintained_exit_success_by_default has been running for over 60 seconds
test unsound_advisories_found_json has been running for over 60 seconds
test version has been running for over 60 seconds
test yanked_exit_failure_deny_yanked has been running for over 60 seconds
test yanked_exit_success_by_default has been running for over 60 seconds
test advisories_found_but_ignored_json ... FAILED
test advisories_found_exit_error ... FAILED
test no_advisories_found_exit_success ... FAILED
test advisories_found_json ... FAILED
test no_advisories_found_empty_json ... FAILED
test no_lockfile_exit_error ... FAILED
test notice_advisories_found_json ... FAILED
test unmaintained_advisories_found_json ... FAILED
test unmaintained_exit_failure_deny_warnings ... FAILED
test unmaintained_exit_success_by_default ... FAILED
test version ... FAILED
test unsound_advisories_found_json ... FAILED
test yanked_exit_failure_deny_yanked ... FAILED
test yanked_exit_success_by_default ... FAILED

failures:

---- advisories_found_but_ignored_json stdout ----
[cargo-audit/tests/acceptance.rs:90] &output = ""
thread 'advisories_found_but_ignored_json' panicked at cargo-audit/tests/acceptance.rs:91:35:
called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- advisories_found_exit_error stdout ----
thread 'advisories_found_exit_error' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- no_advisories_found_exit_success stdout ----
thread 'no_advisories_found_exit_success' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- advisories_found_json stdout ----
thread 'advisories_found_json' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- no_advisories_found_empty_json stdout ----
thread 'no_advisories_found_empty_json' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- no_lockfile_exit_error stdout ----
thread 'no_lockfile_exit_error' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- notice_advisories_found_json stdout ----
thread 'notice_advisories_found_json' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- unmaintained_advisories_found_json stdout ----
thread 'unmaintained_advisories_found_json' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- unmaintained_exit_failure_deny_warnings stdout ----
thread 'unmaintained_exit_failure_deny_warnings' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- unmaintained_exit_success_by_default stdout ----
thread 'unmaintained_exit_success_by_default' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- version stdout ----
thread 'version' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- unsound_advisories_found_json stdout ----
thread 'unsound_advisories_found_json' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- yanked_exit_failure_deny_yanked stdout ----
thread 'yanked_exit_failure_deny_yanked' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }

---- yanked_exit_success_by_default stdout ----
thread 'yanked_exit_success_by_default' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/abscissa_core-0.6.0/src/testing/runner.rs:195:39:
poisoned cmd mutex!: PoisonError { .. }


failures:
    advisories_found_but_ignored_json
    advisories_found_exit_error
    advisories_found_json
    no_advisories_found_empty_json
    no_advisories_found_exit_success
    no_lockfile_exit_error
    notice_advisories_found_json
    unmaintained_advisories_found_json
    unmaintained_exit_failure_deny_warnings
    unmaintained_exit_success_by_default
    unsound_advisories_found_json
    version
    yanked_exit_failure_deny_yanked
    yanked_exit_success_by_default

test result: FAILED. 0 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out; finished in 808.19s

error: test failed, to rerun pass `--test acceptance`
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by tarcieri** [comment]
The real error is here:

```
thread 'advisories_found_but_ignored_json' panicked at cargo-audit/tests/acceptance.rs:91:35:
called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
```

**Comment by Shnatsel** [comment]
By the way, we should do away with the mutexes in tests, now that proper locking is in place.
