### ISSUE TITLE
Failing tests on GNU Guix

### ISSUE THREAD

**Issue by phodina** [rustsec/rustsec#507]
Hi,

I'm porting this crate to GNU Guix. As part of the package definition it's customary to run tests if available.

When I run the tests they unfortunately fail. I expect it's due to the nature of the sandbox as the package does not have network connection. Is it possible to download the CVEs manually (`wget`, `curl`, `git`) and just point `cargo audit` to where it can find them?

```
running 7 tests
+ run: cargo run -- audit --db /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/.tmpUTTX4l --file /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/cargo-audit-0.16.0/tests/support/base64_vuln/Cargo.lock --json --ignore RUSTSEC-2017-0004
test advisories_found_but_ignored_json ... FAILED
test no_advisories_found_empty_json ... FAILED
test advisories_found_json ... FAILED
test no_advisories_found_exit_success ... FAILED
test version ... FAILED
test advisories_found_exit_error ... FAILED
test no_lockfile_exit_error ... FAILED

failures:

---- advisories_found_but_ignored_json stdout ----
thread 'advisories_found_but_ignored_json' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', tests/acceptance.rs:69:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- no_advisories_found_empty_json stdout ----
thread 'no_advisories_found_empty_json' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/cargo-audit-0.16.0/guix-vendor/abscissa_core-0.5.2/src/testing/runner.rs:195:39

---- advisories_found_json stdout ----
thread 'advisories_found_json' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/cargo-audit-0.16.0/guix-vendor/abscissa_core-0.5.2/src/testing/runner.rs:195:39

---- no_advisories_found_exit_success stdout ----
thread 'no_advisories_found_exit_success' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/cargo-audit-0.16.0/guix-vendor/abscissa_core-0.5.2/src/testing/runner.rs:195:39

---- version stdout ----
thread 'version' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/cargo-audit-0.16.0/guix-vendor/abscissa_core-0.5.2/src/testing/runner.rs:195:39

---- advisories_found_exit_error stdout ----
thread 'advisories_found_exit_error' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/cargo-audit-0.16.0/guix-vendor/abscissa_core-0.5.2/src/testing/runner.rs:195:39

---- no_lockfile_exit_error stdout ----
thread 'no_lockfile_exit_error' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /tmp/guix-build-rust-cargo-audit-0.16.0.drv-0/cargo-audit-0.16.0/guix-vendor/abscissa_core-0.5.2/src/testing/runner.rs:195:39


failures:
    advisories_found_but_ignored_json
    advisories_found_exit_error
    advisories_found_json
    no_advisories_found_empty_json
    no_advisories_found_exit_success
    no_lockfile_exit_error
    version

test result: FAILED. 0 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 35.35s
```

**Comment by tarcieri** [comment]
While you can do that, the test suite requires a network connection for integration testing

**Comment by tarcieri** [comment]
You can clone the https://github.com/rustsec/advisory-db repository and use the `--no-fetch` and `--db` arguments to specify an offline database, however those flags can't be used in conjunction with the test suite today, which performs a full integration test which needs a network connection

**Comment by phodina** [comment]
Thanks, the aim of the ticket is to solve the test suite. If that is not possible atm I'm just disable the tests with link to this ticket :-)
