### ISSUE TITLE
[cvss] support cvss3.0 vector with temporal score or environmental metrics

### ISSUE THREAD

**Issue by gcmurphy** [rustsec/rustsec#683]
I'm trying to parse the cvss vector for a collection of GHSA reports. There are some that include temporal scores that cause a failure. Are there any plans on supporting the temporal metric group and environmental metric group from the specification?

As an example taken from: https://github.com/advisories/GHSA-4p9g-qgx9-397p

```rs
use std::str::FromStr;
fn main(){
    let a = cvss::v3::Base::from_str("CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H/E:F/RL:O/RC:C").unwrap();
    println!("{:?}", a);
}
```

Results in this output: 

```
❯ RUST_BACKTRACE=1 cargo run --example cvss
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/cvss`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownMetric { name: "E" }', examples/cvss.rs:3:100
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1078:23
   4: cvss::main
             at ./examples/cvss.rs:3:13
   5: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


```

**Comment by tarcieri** [comment]
We don't currently support Temporal (or Environmental) Scores, only Base Scores.

We would accept a PR to add support, however there is currently no one planning on working on that.

**Comment by gcmurphy** [comment]
No worries. I went off on a bit of tangent and made my own [dodgy version](https://github.com/gcmurphy/cvss) anyway which was good enough for what I was hacking on.
