### ISSUE TITLE
`cargo audit` crashes with compiler error with latest nightly builds

### ISSUE THREAD

**Issue by timfpark** [rustsec/rustsec#726]
Our project has been very happily using `cargo audit` for many months but since approximately August 21st, 2022 it crashes with the following stack trace:

```
    Checking serde_path_to_error v0.1.8
    Checking itertools v0.10.5
    Checking opentelemetry v0.18.0
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:345 ~ tower[226e]::balance::pool::{impl#3}::build) (CanonicalUserTypeAnnotation { user_ty: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: Ty(General(U0)) }], value: TypeOf(DefId(0:232 ~ tower[226e]::balance::p2c::service::{impl#1}::new), UserSubsts { substs: [^0, ^1], user_self_ty: Some(UserSelfTy { impl_def_id: DefId(0:229 ~ tower[226e]::balance::p2c::service::{impl#1}), self_ty: balance::p2c::service::Balance<^2, ^3> }) }) }, span: /Users/timothypark/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/balance/pool/mod.rs:293:22: 293:34 (#0), inferred_ty: fn(std::pin::Pin<std::boxed::Box<balance::pool::PoolDiscoverer<MS, Target, Request>>>) -> balance::p2c::service::Balance<std::pin::Pin<std::boxed::Box<balance::pool::PoolDiscoverer<MS, Target, Request>>>, Request> {balance::p2c::service::Balance::<std::pin::Pin<std::boxed::Box<balance::pool::PoolDiscoverer<MS, Target, Request>>>, Request>::new} }): bad user type AscribeUserType(fn(std::pin::Pin<std::boxed::Box<balance::pool::PoolDiscoverer<MS, Target, Request>>>) -> balance::p2c::service::Balance<std::pin::Pin<std::boxed::Box<balance::pool::PoolDiscoverer<MS, Target, Request>>>, Request> {balance::p2c::service::Balance::<std::pin::Pin<std::boxed::Box<balance::pool::PoolDiscoverer<MS, Target, Request>>>, Request>::new}, DefId(0:232 ~ tower[226e]::balance::p2c::service::{impl#1}::new) UserSubsts { substs: [_, _], user_self_ty: Some(UserSelfTy { impl_def_id: DefId(0:229 ~ tower[226e]::balance::p2c::service::{impl#1}), self_ty: balance::p2c::service::Balance<_, _> }) }, type_of=fn(D) -> balance::p2c::service::Balance<D, Req> {balance::p2c::service::Balance::<D, Req>::new}): NoSolution
  |
  = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:1087:25

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1492:13
stack backtrace:
   0:        0x102f57674 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h73e970e05a6bf6f4
   1:        0x102fa1cb0 - core::fmt::write::hd9cd64c16d8fd98c
   2:        0x102f4a614 - std::io::Write::write_fmt::h5d2b2d095caf1139
   3:        0x102f59ef0 - std::panicking::default_hook::{{closure}}::ha6c7c7f01b1b2a1f
   4:        0x102f59c14 - std::panicking::default_hook::hcaed88806e48b30d
   Compiling which v4.3.0
    Checking jsonwebtoken v8.1.1
   5:        0x10adae84c - rustc_driver[204a304eb552b27e]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x102f5a5b4 - std::panicking::rust_panic_with_hook::hf035e6e087d07291
   7:        0x10eccbc08 - std[c0c9dc31ce531edb]::panicking::begin_panic::<rustc_errors[2a3cc773c9beae6c]::ExplicitBug>::{closure#0}
   8:        0x10eccb3a0 - std[c0c9dc31ce531edb]::sys_common::backtrace::__rust_end_short_backtrace::<std[c0c9dc31ce531edb]::panicking::begin_panic<rustc_errors[2a3cc773c9beae6c]::ExplicitBug>::{closure#0}, !>
   9:        0x10efb8de0 - std[c0c9dc31ce531edb]::panicking::begin_panic::<rustc_errors[2a3cc773c9beae6c]::ExplicitBug>
  10:        0x10ecc3580 - std[c0c9dc31ce531edb]::panic::panic_any::<rustc_errors[2a3cc773c9beae6c]::ExplicitBug>
  11:        0x10ecc6084 - <rustc_errors[2a3cc773c9beae6c]::HandlerInner as core[390033399dd91e36]::ops::drop::Drop>::drop
  12:        0x10add6a18 - core[390033399dd91e36]::ptr::drop_in_place::<rustc_session[75643165ebe3368e]::parse::ParseSess>
  13:        0x10addc960 - <alloc[1508344f4503e9d8]::rc::Rc<rustc_session[75643165ebe3368e]::session::Session> as core[390033399dd91e36]::ops::drop::Drop>::drop
  14:        0x10adc49fc - core[390033399dd91e36]::ptr::drop_in_place::<rustc_interface[3b34bd2c42adabcd]::interface::Compiler>
  15:        0x10adca228 - rustc_interface[3b34bd2c42adabcd]::interface::create_compiler_and_run::<core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>, rustc_driver[204a304eb552b27e]::run_compiler::{closure#1}>
  16:        0x10ae177bc - <scoped_tls[23c3db75e03351d0]::ScopedKey<rustc_span[9eaf7bb8bc869ca5]::SessionGlobals>>::set::<rustc_interface[3b34bd2c42adabcd]::interface::run_compiler<core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>, rustc_driver[204a304eb552b27e]::run_compiler::{closure#1}>::{closure#0}, core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>>
  17:        0x10ade2f2c - std[c0c9dc31ce531edb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3b34bd2c42adabcd]::util::run_in_thread_pool_with_globals<rustc_interface[3b34bd2c42adabcd]::interface::run_compiler<core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>, rustc_driver[204a304eb552b27e]::run_compiler::{closure#1}>::{closure#0}, core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>>::{closure#0}, core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>>
  18:        0x10ade5db0 - <<std[c0c9dc31ce531edb]::thread::Builder>::spawn_unchecked_<rustc_interface[3b34bd2c42adabcd]::util::run_in_thread_pool_with_globals<rustc_interface[3b34bd2c42adabcd]::interface::run_compiler<core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>, rustc_driver[204a304eb552b27e]::run_compiler::{closure#1}>::{closure#0}, core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>>::{closure#0}, core[390033399dd91e36]::result::Result<(), rustc_errors[2a3cc773c9beae6c]::ErrorGuaranteed>>::{closure#1} as core[390033399dd91e36]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  19:        0x102f62450 - std::sys::unix::thread::Thread::new::thread_start::habfef6fa3f2b24db
  20:        0x19ca2826c - __pthread_deallocate

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (750bd1a7f 2022-09-14) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -Z binary-dep-depinfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `tower`
warning: build failed, waiting for other jobs to finish...
```

It does work successfully for the 2022-08-20 nightly build if that is helpful.

**Comment by tarcieri** [comment]
`opentelemetry` is not a dependency of `cargo-audit`.

And judging from the "Checking [package]" it looks like you're running `cargo check` on your own project.

Regardless, nightly compile errors should be reported upstream to rustc. Even if `cargo-audit` were implicated, we can't do anything about bugs in the compiler.
