### ISSUE TITLE
cargo-audit: macOS build failures in CI when testing `auditable`

### ISSUE THREAD

**Issue by tarcieri** [rustsec/rustsec#795]
https://github.com/rustsec/rustsec/actions/runs/3992756517/jobs/6848877427

```
failures:

---- auditable_binary_without_vulnerabilities_passes stdout ----
thread 'auditable_binary_without_vulnerabilities_passes' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', cargo-audit/tests/binary_scanning.rs:66:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- auditable_binary_with_vulnerabilities_fails stdout ----
thread 'auditable_binary_with_vulnerabilities_fails' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/abscissa_core-0.6.0/src/testing/runner.rs:195:39

---- panicking_binary_with_vulnerabilities_fails stdout ----
thread 'panicking_binary_with_vulnerabilities_fails' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/abscissa_core-0.6.0/src/testing/runner.rs:195:39

---- panicking_binary_without_vulnerabilities_passes stdout ----
thread 'panicking_binary_without_vulnerabilities_passes' panicked at 'poisoned cmd mutex!: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/abscissa_core-0.6.0/src/testing/runner.rs:195:39


failures:
    auditable_binary_with_vulnerabilities_fails
    auditable_binary_without_vulnerabilities_passes
    panicking_binary_with_vulnerabilities_fails
    panicking_binary_without_vulnerabilities_passes
```

**Comment by tarcieri** [comment]
Unless there's a quick fix, I'd suggest disabling the `--all-features` test on macOS for now so it's not blocking other development

**Comment by tarcieri** [comment]
I opened #796 which makes various changes to the CI config, including re-enabling the Windows build

**Comment by Shnatsel** [comment]
Riiiight, of course the proprietary platform I don't have access to will fail :facepalm: 

Time to take up that offer from a Mac renting company and put an ad for them in `cargo-auditable`'s README, I suppose.

**Comment by Shnatsel** [comment]
All tests pass on a local Mac: https://rust-lang.zulipchat.com/#narrow/stream/146229-wg-secure-code/topic/rustsec.20good.20first.20issues/near/328843058

I'm going to re-enable CI and see if anything fails, hopefully the issue was transient.

**Comment by tarcieri** [comment]
@Shnatsel FYI, I think they might be sporadic.

Maybe try running the local tests in a loop.

**Comment by Shnatsel** [comment]
I've run tests locally in a loop overnight (albeit on Linux) and didn't see a single failure, so I'm going to go ahead and assume whatever it is was transient.

**Comment by tarcieri** [comment]
It failed again: https://github.com/rustsec/rustsec/actions/runs/4398237198/jobs/7701931635

**Comment by Shnatsel** [comment]
It seems I can view the logs for all the other jobs, but not this one? There's no `>` element to expand the logs on the failed job.

![Screenshot from 2023-03-12 17 16 32](https://user-images.githubusercontent.com/291257/224557730-2a7d34f0-b5f3-48c8-863c-7ec2608b7de8.png)

**Comment by Shnatsel** [comment]
Also, tests for `auditable` passed just fine - they're enabled by default now, so even `cargo test --release` runs them, and they show success status in the logs.

The non-default feature that must be causing failures is `cargo audit fix`
